Print keychain_get_value error to stderr

diff --git a/functions/keychain_get_value b/functions/keychain_get_value
--- a/functions/keychain_get_value
+++ b/functions/keychain_get_value
@@ -37,10 +37,10 @@ _sec=$(eval "${sec_find_cmd[@]}" 2>&1)
 if test $? -eq 0; then
   print "${_sec}";
 else
-  printf 'Unable to get keychain value for (service:%s|account:%s|comment:%s|label:%s);\n%s' \
+  (printf 'Unable to get keychain value for (service:%s|account:%s|comment:%s|label:%s);\n%s' \
     ${s_service} \
     ${a_account} \
     ${j_comment} \
     ${l_label} \
-    "${_sec}"
+    "${_sec}" ) >&2
 fi
